import { CtaLink } from "@/components/cta-link";

const needs = ["Jenis pekerjaan", "Muatan & konfigurasi", "Area operasional"] as const;
const families = [
  ["Canter", "canter", "/mitsubishi-fuso/canter/"],
  ["Fighter X", "fighter-x", "/mitsubishi-fuso/fighter-x/"],
  ["Tractor Head", "tractor-head", "/mitsubishi-fuso/tractor-head/"],
  ["eCanter", "ecanter", "/mitsubishi-fuso/ecanter/"],
] as const;
const trust = ["Informasi terstruktur", "Kebutuhan bisnis lebih dulu", "Jalur konsultasi jelas"] as const;

export default function Home() {
  return (
    <main id="main-content" className="site-main">
      <section className="home-hero" aria-labelledby="hero-title"><div className="home-hero-grid"><div><div className="eyebrow">Mitsubishi Fuso untuk kebutuhan bisnis</div><h1 id="hero-title">Temukan Fuso yang sesuai dengan kebutuhan bisnis Anda.</h1><p className="hero-copy">Mulai dari kebutuhan operasional Anda, pelajari pilihan keluarga kendaraan, lalu lanjutkan ke informasi harga atau konsultasi sales.</p><div className="cta-row" aria-label="Pilihan tindakan utama"><CtaLink href="/harga-fuso/" variant="primary">Cek Harga</CtaLink><CtaLink href="/mitsubishi-fuso/" variant="secondary">Cari Fuso Saya</CtaLink><CtaLink href="/hubungi-sales/" variant="dark">Minta Penawaran</CtaLink></div></div><div className="hero-panel" aria-hidden="true"><span className="hero-panel-index">01</span><span className="hero-panel-label">FusoCenter</span><span className="hero-panel-line" /><span className="hero-panel-caption">Business vehicle discovery</span></div></div></section>
      <section className="home-section home-section-muted" aria-labelledby="needs-title"><div className="section-heading"><div><div className="section-kicker">Mulai dari kebutuhan</div><h2 id="needs-title">Temukan titik awal untuk bisnis Anda.</h2></div><p className="section-copy">Pilih konteks yang paling dekat dengan kebutuhan Anda. FusoCenter membantu menata langkah pencarian berikutnya.</p></div><div className="card-grid card-grid-three">{needs.map((title, i) => <article className="info-card" key={title}><span className="card-number" aria-hidden="true">0{i + 1}</span><h3>{title}</h3><p>Mulai dari konteks penggunaan yang ingin Anda dukung.</p><a className="text-link" href="/solusi-bisnis/">Cari Solusi Bisnis <span aria-hidden="true">↗</span></a></article>)}</div></section>
      <section className="home-section" aria-labelledby="families-title"><div className="section-heading"><div><div className="section-kicker">Keluarga kendaraan</div><h2 id="families-title">Pilih arah pencarian Fuso Anda.</h2></div><p className="section-copy">Keluarga kendaraan berikut adalah titik awal taxonomy FusoCenter. Detail produk akan mengikuti data yang disetujui.</p></div><div className="card-grid card-grid-four">{families.map(([name, slug, href], i) => <a className="family-card" href={href} key={slug}><span className="family-index" aria-hidden="true">0{i + 1}</span><h3>{name}</h3><p>Mulai jelajahi keluarga kendaraan {name}.</p><span className="text-link">Lihat keluarga <span aria-hidden="true">↗</span></span></a>)}</div></section>
      <section className="discovery-band" aria-labelledby="find-title"><div className="discovery-band-inner"><div><div className="section-kicker">Cari Fuso Saya</div><h2 id="find-title">Temukan keluarga kendaraan yang mendekati kebutuhan Anda.</h2><p>Mulai pencarian berdasarkan kebutuhan bisnis dan lanjutkan ke jalur informasi yang relevan.</p></div><CtaLink href="/mitsubishi-fuso/" variant="dark">Cari Fuso Saya</CtaLink></div></section>
      <section className="home-section home-section-muted" aria-labelledby="price-title"><div className="section-heading"><div><div className="section-kicker">Informasi komersial</div><h2 id="price-title">Harga dan promo, saat Anda membutuhkannya.</h2></div><p className="section-copy">Informasi harga dan program akan mengikuti data yang telah disetujui dan diperbarui.</p></div><div className="route-grid"><article className="route-card"><h3>Harga Fuso</h3><p>Temukan jalur untuk meminta informasi harga terbaru.</p><CtaLink href="/harga-fuso/">Cek Harga Fuso</CtaLink></article><article className="route-card"><h3>Promo Fuso</h3><p>Lihat halaman program yang tersedia ketika sudah dipublikasikan.</p><CtaLink href="/promo-fuso/" variant="secondary">Lihat Promo Fuso</CtaLink></article></div></section>
      <section className="home-section" aria-labelledby="solutions-title"><div className="split-callout"><div><div className="section-kicker">Business solutions</div><h2 id="solutions-title">Pilih solusi yang berangkat dari cara bisnis Anda bekerja.</h2><p>Jelajahi kebutuhan bisnis sebagai langkah awal sebelum masuk ke pilihan kendaraan yang lebih spesifik.</p></div><div className="cta-row"><CtaLink href="/solusi-bisnis/">Cari Solusi Bisnis</CtaLink><CtaLink href="/karoseri/" variant="secondary">Lihat Karoseri</CtaLink></div></div></section>
      <section className="home-section home-section-muted" aria-labelledby="trust-title"><div className="section-heading"><div><div className="section-kicker">Mengapa FusoCenter</div><h2 id="trust-title">Pengalaman pencarian yang lebih terarah.</h2></div><p className="section-copy">FusoCenter dirancang untuk membantu Anda berpindah dari kebutuhan bisnis menuju langkah konsultasi dengan jelas.</p></div><div className="card-grid card-grid-three">{trust.map((title, i) => <article className="info-card" key={title}><span className="card-number" aria-hidden="true">0{i + 1}</span><h3>{title}</h3><p>Pengalaman informasi yang rapi untuk membantu langkah berikutnya.</p></article>)}</div></section>
      <section className="home-section" aria-labelledby="financing-title"><div className="split-callout split-callout-dark"><div><div className="section-kicker">Rencana pembelian</div><h2 id="financing-title">Rencanakan pembelian kendaraan bisnis Anda.</h2><p>Gunakan jalur simulasi sebagai langkah persiapan sebelum berkonsultasi.</p></div><CtaLink href="/simulasi-kredit-fuso/">Hitung Cicilan</CtaLink></div></section>
      <section className="home-section home-section-muted" aria-labelledby="dealer-title"><div className="section-heading"><div><div className="section-kicker">Langkah berikutnya</div><h2 id="dealer-title">Butuh lokasi atau percakapan langsung?</h2></div><p className="section-copy">Pilih jalur yang sesuai dengan tahap pencarian Anda.</p></div><div className="route-grid"><article className="route-card"><h3>Cari Dealer Fuso</h3><p>Temukan jalur menuju informasi dealer.</p><CtaLink href="/dealer-fuso/" variant="secondary">Cari Dealer Fuso</CtaLink></article><article className="route-card route-card-accent"><h3>Hubungi Sales</h3><p>Bicarakan kebutuhan bisnis Anda dengan tim sales.</p><CtaLink href="/hubungi-sales/" variant="dark">Hubungi Sales</CtaLink></article></div></section>
      <section className="home-section" aria-labelledby="insights-title"><div className="split-callout"><div><div className="section-kicker">Business insights</div><h2 id="insights-title">Ikuti insight untuk kebutuhan bisnis Anda.</h2><p>Artikel dan insight akan dihadirkan dari CMS ketika sudah tersedia.</p></div><CtaLink href="/artikel/" variant="secondary">Baca Artikel</CtaLink></div></section>
      <section className="final-cta" aria-labelledby="final-title"><div className="final-cta-inner"><div className="section-kicker">FusoCenter</div><h2 id="final-title">Siap menemukan Fuso untuk kebutuhan bisnis Anda?</h2><div className="cta-row"><CtaLink href="/mitsubishi-fuso/">Cari Fuso Saya</CtaLink><CtaLink href="/hubungi-sales/" variant="secondary">Minta Penawaran</CtaLink></div></div></section>
    </main>
  );
}
